import { RoleScript } from '../types';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

/**
 * Print helper for generating print-friendly HTML and managing print/PDF export
 */
export const PrintService = {
  /**
   * Generate print-friendly HTML for a role script
   */
  generateHTML(role: RoleScript): string {
    const tipsHTML =
      role.tips && role.tips.length > 0
        ? `
        <div style="margin-top: 30px; padding: 20px; background-color: #f0f8ff; border-left: 4px solid #007AFF;">
          <h3 style="color: #007AFF; margin-top: 0;">💡 Tips for Success</h3>
          <ul style="line-height: 1.8;">
            ${role.tips.map((tip) => `<li>${tip}</li>`).join('')}
          </ul>
        </div>
      `
        : '';

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${role.name}</title>
          <style>
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              line-height: 1.6;
              color: #333;
              margin: 40px;
              max-width: 800px;
            }
            h1 {
              color: #007AFF;
              border-bottom: 3px solid #007AFF;
              padding-bottom: 10px;
              font-size: 28px;
            }
            .subtitle {
              color: #666;
              font-size: 16px;
              margin-bottom: 20px;
            }
            .script-content {
              background-color: #f9f9f9;
              padding: 20px;
              border-radius: 8px;
              font-family: 'Courier New', monospace;
              white-space: pre-wrap;
              word-wrap: break-word;
              line-height: 1.8;
              margin: 20px 0;
            }
            @media print {
              body { margin: 20px; }
              .script-content { page-break-inside: avoid; }
            }
          </style>
        </head>
        <body>
          <h1>${role.name}</h1>
          <div class="subtitle">${role.description}</div>
          
          <h3 style="color: #333; margin-top: 30px;">Script</h3>
          <div class="script-content">${role.script}</div>
          
          ${tipsHTML}
          
          <div style="margin-top: 40px; text-align: center; color: #999; font-size: 12px;">
            <p>Generated by ToastEase | Toastmasters Role Scripts</p>
          </div>
        </body>
      </html>
    `;
  },

  /**
   * Print a role script to PDF
   */
  async printToPDF(role: RoleScript): Promise<void> {
    try {
      const html = this.generateHTML(role);
      const result = await Print.printAsync({
        html,
        printerUrl: undefined,
      });
      return result;
    } catch (error) {
      console.error('Error printing:', error);
      throw error;
    }
  },

  /**
   * Generate PDF and share it
   */
  async sharePDF(role: RoleScript): Promise<void> {
    try {
      const html = this.generateHTML(role);
      const { uri } = await Print.printToFileAsync({ html });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: `Share ${role.name}`,
        });
      } else {
        console.warn('Sharing not available on this device');
      }
    } catch (error) {
      console.error('Error sharing PDF:', error);
      throw error;
    }
  },

  /**
   * Export all scripts to a single PDF document
   */
  async exportAllScripts(scripts: RoleScript[]): Promise<void> {
    try {
      const htmlContent = `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>Toastmasters Role Scripts</title>
            <style>
              body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                line-height: 1.6;
                color: #333;
              }
              .cover-page {
                text-align: center;
                padding: 100px 20px;
                page-break-after: always;
              }
              .cover-page h1 {
                font-size: 48px;
                color: #007AFF;
                margin: 20px 0;
              }
              .role-section {
                page-break-before: always;
                margin: 40px 20px;
              }
              .role-section h2 {
                color: #007AFF;
                border-bottom: 2px solid #007AFF;
                padding-bottom: 10px;
              }
              .role-description {
                font-style: italic;
                color: #666;
                margin: 10px 0;
              }
              .script {
                background-color: #f9f9f9;
                padding: 15px;
                border-radius: 5px;
                font-family: 'Courier New', monospace;
                white-space: pre-wrap;
                margin: 15px 0;
              }
              .tips {
                margin-top: 20px;
                padding: 15px;
                background-color: #f0f8ff;
                border-left: 4px solid #007AFF;
              }
              .tips h4 {
                color: #007AFF;
              }
              .tips ul {
                padding-left: 20px;
              }
              .tips li {
                margin: 8px 0;
              }
            </style>
          </head>
          <body>
            <div class="cover-page">
              <h1>🎤 Toastmasters Role Scripts</h1>
              <p style="font-size: 20px; color: #666;">Complete Guide to All Standard Roles</p>
              <p style="margin-top: 40px; color: #999;">Generated by ToastEase</p>
            </div>
            
            ${scripts
              .map(
                (script) => `
              <div class="role-section">
                <h2>${script.name}</h2>
                <div class="role-description">${script.description}</div>
                
                <h4 style="margin-top: 20px;">Script:</h4>
                <div class="script">${script.script}</div>
                
                ${
                  script.tips && script.tips.length > 0
                    ? `
                  <div class="tips">
                    <h4>💡 Tips for Success</h4>
                    <ul>
                      ${script.tips.map((tip) => `<li>${tip}</li>`).join('')}
                    </ul>
                  </div>
                `
                    : ''
                }
              </div>
            `
              )
              .join('')}
          </body>
        </html>
      `;

      const result = await Print.printToFileAsync({ html: htmlContent });
      return result;
    } catch (error) {
      console.error('Error exporting all scripts:', error);
      throw error;
    }
  },
};
